# Generated by Django 3.2.7 on 2023-05-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210720_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='height',
        ),
        migrations.RemoveField(
            model_name='data',
            name='sex',
        ),
        migrations.AddField(
            model_name='data',
            name='english_level',
            field=models.PositiveIntegerField(choices=[(0, 'Yes'), (1, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='gpa',
            field=models.FloatField(null=True),
        ),
    ]
