# Generated by Django 3.2.7 on 2023-05-13 22:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20230514_0216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='english_level',
            new_name='english',
        ),
        migrations.AlterField(
            model_name='data',
            name='age',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(65)]),
        ),
    ]
